### ISSUE TITLE
DispatcherFilter does not do useful controller callbacks

### ISSUE THREAD

**Issue by hekep** [dereuromark/cakephp-cache#1]
DispatcherFilter does not Controller startupProcess() function,
https://github.com/cakephp/cakephp/blob/master/src/Controller/Controller.php#L471

which fires up useful components, such as ACL, to check if user has right to view the cached content. 

User with correct access may log out, and the cached version stays on disk. Unauthorized user comes and views cached version. 

So use it only in "public controllers" or add such ACL check functionality. Cakephp 2.x cache helper does controller some callbacks. In my opinion every corporate php framework should do it.

**Comment by hekep** [comment]
2.X startupProcess()  right there:
https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/View/Helper/CacheHelper.php#L328

**Comment by dereuromark** [comment]
That is a valid point.
The docs should point out that this only makes sense for public views.

**Comment by dereuromark** [comment]
Resolved with https://github.com/dereuromark/cakephp-cache/commit/57616045fe4c75e4c5b959d6971f2165e0ffa445 for now.
Please open if you have ideas on how to approach this incl. auth.
