### ISSUE TITLE
Refactor the code to use cache engines

### ISSUE THREAD

**Issue by burzum** [dereuromark/cakephp-cache#11]
Right now the code relies on the hard coded file based caching solution.

It would be much better if the current file based implementation would be turned into a cache engine or simply the existing file based engine could be used.

I would expect the plugin to check for a 'fullPage' cache config, if it doesn't find it, either throw an exception or use `default`. Guess using `default` is OK in this case.

**Comment by dereuromark** [comment]
PR welcome 

But this could conflict with the current way of setting cache time on a per action basis:

    'actions' => ['report', 'view' => DAY, 'index' => HOUR],

Any idea how this could be handled then?

Maybe we could combine it and still store the cache time inside the cache content (at the beginning) and allow this to be used to further restrict (shorter cache time).
Then we can also set cache configs, and only fall back to this file strategy if none are defined.

We would just need to wrap the caching part, so the caching strategy is encapsulated inside.
