### ISSUE TITLE
Allow different cache times for different URLs

### ISSUE THREAD

**Issue by burzum** [dereuromark/cakephp-cache#12]
The title says it all

**Comment by dereuromark** [comment]
PR welcome 

Currently it already uses 

    'actions' => ['report', 'view' => DAY, 'index' => HOUR],

which is this as basic version.

**Comment by dereuromark** [comment]
But how would this work? You can also just give a rough sketch of it.
I think the main issue is here to "detect" the configs per URL.
Do you match on controller level, action level?

Also, does this conflict with https://github.com/dereuromark/cakephp-cache/issues/11 and cache engine config? As that one usually has one defined length.

**Comment by dereuromark** [comment]
Still part of https://github.com/dereuromark/cakephp-cache/pull/21
