### ISSUE TITLE
Cache is writed with $_POST request

### ISSUE THREAD

**Issue by Aerue** [dereuromark/cakephp-cache#17]
There is a bug in logic of the [shutdown](https://github.com/dereuromark/cakephp-cache/blob/master/src/Controller/Component/CacheComponent.php#L29) function. Sending a POST request from a view get it cached... Then the next GET request load the recent cached view which is the POST result.

The [_isActionCachable](https://github.com/dereuromark/cakephp-cache/blob/master/src/Controller/Component/CacheComponent.php#L56) should check the conditions of the when in the dispacther too.

This bug happens when you want only cache GET request and the configuration in the initialize didn't specify any actions.

This result of the view to be cached with POST result.

**Comment by dereuromark** [comment]
That is true.

		$middleware = new CacheMiddleware([
			'when' => function (Request $request, Response $response) {
				return $request->is('get');
			},
		]);

is the only part where we check the type so far, and that is not enough.

Can you check if https://github.com/dereuromark/cakephp-cache/commit/bd25861803d44374b08bb250d47eecc5e9cce2ca fixes it?
