### ISSUE TITLE
Error: Argument 2 passed to .. :App\{closure}() must be an instance of Cake\Http\Response

### ISSUE THREAD

**Issue by fin-k** [dereuromark/cakephp-cache#20]
Please help, I got this error.
> Argument 2 passed to App\Application::App\{closure}() must be an instance of Cake\Http\Response, instance of Cake\Http\ServerRequest given, called in ...... \cake4_test\vendor\dereuromark\cakephp-cache\src\Routing\Middleware\CacheMiddleware.php on line 57

Cake version is 4.0.5 and plugin version is 1.0.0-beta

**Comment by dereuromark** [comment]
What cake version and plugin version?
What is your code here?

**Comment by fin-k** [comment]
> What cake version and plugin version?
> What is your code here?

**Comment by fin-k** [comment]
I edit the descriptions, sorry i accidentally close the issue.

**Comment by dereuromark** [comment]
You didnt post your code.

**Comment by fin-k** [comment]
oh sorry, this is on application.php:

`use Cache\Routing\Middleware\CacheMiddleware;
use Cake\Http\ServerRequest;
use Cake\Http\Response;
...
public function middleware(MiddlewareQueue $middlewareQueue): MiddlewareQueue
    {
        $middlewareQueue
            // Catch any exceptions in the lower layers,
            // and make an error page/response
            ->add(new ErrorHandlerMiddleware(Configure::read('Error')))

            // Handle plugin/theme assets like CakePHP normally does.
            ->add(new AssetMiddleware([
                'cacheTime' => Configure::read('Asset.cacheTime'),
            ]))
            ->add(new CacheMiddleware([
                'when' => function (ServerRequest $request, Response $response) {
                    return $request->is('get');
                },
            ]))

            // Add routing middleware.
            // If you have a large number of routes connected, turning on routes
            // caching in production could improve performance. For that when
            // creating the middleware instance specify the cache config name by
            // using it's second constructor argument:
            // `new RoutingMiddleware($this, '_cake_routes_')`
            ->add(new RoutingMiddleware($this));

        return $middlewareQueue;
    }`

**Comment by fin-k** [comment]
and this is on PagesController.php.
` public function initialize()
    {
        parent::initialize();

        $this->loadComponent('Cache.Cache', [

            'force' => true,
            'actions' => ['test' => DAY],
        ]);
    }
`

**Comment by dereuromark** [comment]
Your when is the problem and not needed anymore. It does that on its own.

**Comment by fin-k** [comment]
Could you give me example of the right code?

**Comment by dereuromark** [comment]
Remove the config in it.

**Comment by fin-k** [comment]
Thanks it works. 

I see the code on CacheMiddleware.php that calls $when($request, $request), I tried changing it to $when($request, $response) and it also works. But if I change the code will it mess something else?

![image](https://user-images.githubusercontent.com/10423383/79043465-8419ad00-7c29-11ea-9248-4aaab986aee3.png)

**Comment by dereuromark** [comment]
Sry, that was a mistake, only one argument should be used here
See https://github.com/dereuromark/cakephp-cache/commit/4788bb6fcc40f9bd075dd0f7fe3fc9681cd19aec
I fixed the docs.

You don't need any config here at all. It by default only gets invoked for GET requests, as per HTTP spec for caching (POST requests should never be cached).

Thanks for the report. I release a new tag - RC now
