### ISSUE TITLE
File name too long inside error.log

### ISSUE THREAD

**Issue by NewtonMan** [dereuromark/cakephp-cache#24]
I found a bug that does not generate a cached version of the requested page because the generated filename is to long.

Another important point is that store a huge number of files in one folder causes inodes problems to the system disk, I will try to make some changes then send a PR to this project.

Logs:
`
2020-12-02 15:00:36 Warning: Warning (2): file_put_contents(/var/www/vhosts/promoview.com.br/www.promoview.com.br/tmp/cache/views/categoria-digital-smartphones-serao-os-protagonistas-das-vendas-digitais-de-natal-html-utm-source-ActiveCampaign-utm-medium-email-utm-content-Score-Group-apresenta-a-2a-edi-C3-A7-C3-A3o-do-Pulso-3B-Painel-que-tosse-conscientiza-sobre-o-distanciamento-social-3B-utm-campaign-Newsletter-Di-C3-A1ria-02-2F12-2F2020.html): failed to open stream: File name too long in [/var/www/vhosts/promoview.com.br/www.promoview.com.br/vendor/dereuromark/cakephp-cache/src/Controller/Component/CacheComponent.php, line 120]
Request URL: /categoria/digital/smartphones-serao-os-protagonistas-das-vendas-digitais-de-natal.html?utm_source=ActiveCampaign&utm_medium=email&utm_content=Score+Group+apresenta+a+2a+edi%C3%A7%C3%A3o+do+Pulso%3B++Painel+que+tosse++conscientiza+sobre+o+distanciamento+social%3B&utm_campaign=Newsletter+Di%C3%A1ria+02%2F12%2F2020
Client IP: 189.100.68.224
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 159
file_put_contents - [internal], line ??
Cache\Controller\Component\CacheComponent::_writeFile() - ROOT/vendor/dereuromark/cakephp-cache/src/Controller/Component/CacheComponent.php, line 120
Cache\Controller\Component\CacheComponent::shutdown() - ROOT/vendor/dereuromark/cakephp-cache/src/Controller/Component/CacheComponent.php, line 50
Cake\Event\EventManager::_callListener() - CORE/src/Event/EventManager.php, line 353
Cake\Event\EventManager::dispatch() - CORE/src/Event/EventManager.php, line 330
Cake\Controller\Controller::dispatchEvent() - CORE/src/Event/EventDispatcherTrait.php, line 114
Cake\Controller\Controller::shutdownProcess() - CORE/src/Controller/Controller.php, line 700
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 129
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 94
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 235
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Middleware\CsrfProtectionMiddleware::__invoke() - CORE/src/Http/Middleware/CsrfProtectionMiddleware.php, line 108
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 168
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
AssetCompress\Middleware\AssetCompressMiddleware::__invoke() - ROOT/vendor/markstory/asset_compress/src/Middleware/AssetCompressMiddleware.php, line 57
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 96
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cache\Routing\Middleware\CacheMiddleware::__invoke() - ROOT/vendor/dereuromark/cakephp-cache/src/Routing/Middleware/CacheMiddleware.php, line 67
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 97
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 98
[main] - ROOT/webroot/index.php, line 40
`

**Comment by dereuromark** [comment]
We should first fix this for master and then backport it.

**Comment by NewtonMan** [comment]
I dont think the order is relevant, as I am using version 3 in most projects I started on that, but I also have implemented the same adjusts to master for cake v4, if anyone have any sujestion please attach in this issue

**Comment by dereuromark** [comment]
Should be fixed with https://github.com/dereuromark/cakephp-cache/commit/7592de1bcaf12d9a6e5006e14e1c4f19007b8efa
Do you want to backport this to 3.x?

**Comment by jaykay-design** [comment]
I was about to backport it to 3.x but I found an issue with the 4.x code.
To me it looks like the keyGenreator is used in the CacheComponent but not in the CacheMiddleware. Maybe I'm missing something but I don't think this is finished yet.

The configuration is a bit difficult now, I think. Assuming the keyGenerator is set up through the middleware and then again in the component then this could lead to having different keyGenerators depending on where the component is used and how it is configured.

Maybe it would make sense to only have it configured in the middleware and then pass it down to the component?

**Comment by dereuromark** [comment]
Config it through app.php. then it is always the same
As for the missing part, you can pr that or i will look into it on the weekend.

**Comment by dereuromark** [comment]
So since you opened a backport, i guess 4.x master is all good then?

**Comment by jaykay-design** [comment]
I think the 4.x branch suffers from the same issue. If one decides to set up the key generator thought the middleware then the component won't know about it. Same issue the other way around and for the prefix configuration.

We could use the same "hack" I used in the 3.x branch to make sure the key generator is set to the same wherever it is set up but to be honest I would try to force the configuration to be set in the right place by the user.

Global configuration would be:
- all except actions

Middleware:
- none

Component:
- duration (override global)
- actions
- when (override global)
- compress (override global)
- force (override global)

Should one try to set up the middleware with a configuration then we would issue a warning.

These might be breaking changes, not sure.
