### ISSUE TITLE
Reset cache

### ISSUE THREAD

**Issue by EricRKLS** [dereuromark/cakephp-cache#30]
Maybe there already is a way to do this but it would be nice to have an option to refresh the cache when for example a certain URL parameter is passed.

We are using this plugin for a customer that is requesting the possibility to refresh the cache for certain pages manually. Maybe it's already possible to trigger refreshing of the cache from the controller? Then we could implement the rest ourselves.

**Comment by dereuromark** [comment]
From what I know this is always possible two ways:
- Busting the cache (forcing a re-cache on next page load) by removing the file manually
- Warming the cache by re-building the cache file so next page load would just the new updated cache file

The first works for all low and medium traffic pages, the latter is recommended for high traffic.

You can either build a tool for yourself that does these, or you could make a PR for this plugin to enhance and support one or both of those functionalities.

The shell has already certain capabilities for the first scenario: https://github.com/dereuromark/cakephp-cache/blob/master/src/Shell/CacheShell.php#L107
See https://github.com/dereuromark/cakephp-cache/blob/master/docs/Full-page.md#clear-the-cache
You can see if we should also update documentation here a bit.

The cache warming is more difficult to implement as it needs to run the whole request to build the full result.
So often this is done by just fake opening the URL from a CLI script after busting the cache, or having a ?reset-cache=1 attached that could rebuild and overwrite right away (to avoid side effects).

**Comment by EricRKLS** [comment]
Thanks for the quick answer! Bursting the cache seems like a fine option. Maybe I'll contribute to the project when I have some spare time to make it possible to clear the cache for the current page using a function from the CacheComponent for example.

**Comment by dereuromark** [comment]
All right, closing then for now.

**Comment by dereuromark** [comment]
PS: https://github.com/dereuromark/cakephp-cache/releases/tag/1.1.0 was released. forgot those changes back when I did them.
