### ISSUE TITLE
prefix not working in cake-3

### ISSUE THREAD

**Issue by apps4web** [dereuromark/cakephp-cache#35]
I use the Full Page example.
Without the prefix everything works perfectly.
But I have 2 domains with some differences in de head, so I use prefix to create a html view file for both domains.
Files are being created as expected, but they are ignored and recreated on each request.

In my Controller I have:

$this->loadComponent('Cache.Cache', [
            'actions' => ['view', 'index'],
            'compress' => true, 
            'force' => true
        ]);
Configure::write('Cache.prefix', Configure::read('domain.id'));

How can I tell Cache that it should look for [id]-[template]?

**Comment by dereuromark** [comment]
I havent worked with Cake3 in a long time
You might want to check with the author or https://github.com/dereuromark/cakephp-cache/pull/34 and maybe align hre on making PRs
I am happy to merge and release any fixes here.

**Comment by apps4web** [comment]
Thanx for the reply.
All that needs to be done is to these lines to CacheMiddleware.php on Line 112:
```php
if ($this->getConfig('prefix')) {
    $prefix = $this->getConfig('prefix');
}
```
Before:
```php
$prefix = Configure::read('Cache.prefix');
$keyGenerator = $this->getConfig('keyGenerator');
```
After:
```php
$prefix = Configure::read('Cache.prefix');
if ($this->getConfig('prefix')) {
    $prefix = $this->getConfig('prefix');
}
$keyGenerator = $this->getConfig('keyGenerator');
```
so that if the prefix is added from Application middleware() it will stay intact

**Comment by dereuromark** [comment]
Please make a PR - that is easier to review, approve and merge.
We also need to check if the same issue applies to master (and current 4.x), if so that should also be fixed (ideally first, but can also come 2nd).

**Comment by apps4web** [comment]
sorry, I'm not familier with working on repositories of others.
I tried to push, but was denied
remote: Permission to dereuromark/cakephp-cache.git denied to apps4web.
fatal: unable to access 'https://github.com/dereuromark/cakephp-cache.git/': The requested URL returned error: 403

**Comment by dereuromark** [comment]
You need to fork it, push it there, once you are in the github branch it will show you a PR to upstream to click.

**Comment by dereuromark** [comment]
I guess this is fixed in master though? https://github.com/dereuromark/cakephp-cache/blob/master/src/Routing/Middleware/CacheMiddleware.php#L76
So only applies to cake3 branch this issue?

**Comment by apps4web** [comment]
thanx!
Yes, looks like it is just not implemented in cake3.
Just sent a PR for cake3 branch

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-cache/releases/tag/0.5.1

**Comment by apps4web** [comment]
thanx a lot mark
